apiVersion: v1
kind: Pod
metadata:
  name: coupon-hunter
spec:
  containers:
    - name: coupon-hunter-container
      image: nginx
      volumeMounts:
        - mountPath: /coupons
          name: coupons-volume
      securityContext:
        privileged: true
  volumes:
    - name: coupons-volume
      hostPath:
        path: /etc/hue/data/coupons

        